export CPU = mcs51
export SIZE ?= $(PREFIX)size
export OBJCOPY ?= $(PREFIX)objcopy

# Set default port depending on operating system (serial)
PORT_LINUX ?= /dev/ttyACM0

#setup serial terminal
include ${RIOTBOARD}/Makefile.include.serial
