export CPU       = 8051
#export CPU_MODEL = 8051

# set default port depending on operating system
PORT_LINUX  ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

